# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WithdrawUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_digWithdraw(object):
    def setupUi(self, digWithdraw):
        digWithdraw.setObjectName("digWithdraw")
        digWithdraw.resize(403, 283)
        self.lblBalance_2 = QtWidgets.QLabel(digWithdraw)
        self.lblBalance_2.setGeometry(QtCore.QRect(80, 60, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblBalance_2.setFont(font)
        self.lblBalance_2.setObjectName("lblBalance_2")
        self.btnOK = QtWidgets.QPushButton(digWithdraw)
        self.btnOK.setGeometry(QtCore.QRect(160, 190, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnOK.setFont(font)
        self.btnOK.setObjectName("btnOK")
        self.lblCustomerName_3 = QtWidgets.QLabel(digWithdraw)
        self.lblCustomerName_3.setGeometry(QtCore.QRect(10, 30, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblCustomerName_3.setFont(font)
        self.lblCustomerName_3.setObjectName("lblCustomerName_3")
        self.txtamount = QtWidgets.QLineEdit(digWithdraw)
        self.txtamount.setGeometry(QtCore.QRect(120, 130, 151, 41))
        self.txtamount.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.txtamount.setObjectName("txtamount")
        self.lblCustomerName = QtWidgets.QLabel(digWithdraw)
        self.lblCustomerName.setGeometry(QtCore.QRect(100, 30, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblCustomerName.setFont(font)
        self.lblCustomerName.setText("")
        self.lblCustomerName.setObjectName("lblCustomerName")
        self.lblError = QtWidgets.QLabel(digWithdraw)
        self.lblError.setGeometry(QtCore.QRect(20, 240, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lblError.setFont(font)
        self.lblError.setText("")
        self.lblError.setObjectName("lblError")
        self.lblBalance_3 = QtWidgets.QLabel(digWithdraw)
        self.lblBalance_3.setGeometry(QtCore.QRect(110, 90, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblBalance_3.setFont(font)
        self.lblBalance_3.setObjectName("lblBalance_3")
        self.btnExit = QtWidgets.QPushButton(digWithdraw)
        self.btnExit.setGeometry(QtCore.QRect(330, 250, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnExit.setFont(font)
        self.btnExit.setObjectName("btnExit")

        self.retranslateUi(digWithdraw)
        QtCore.QMetaObject.connectSlotsByName(digWithdraw)

    def retranslateUi(self, digWithdraw):
        _translate = QtCore.QCoreApplication.translate
        digWithdraw.setWindowTitle(_translate("digWithdraw", "Withdraw Panel"))
        self.lblBalance_2.setText(_translate("digWithdraw", "Enter the amount withdraw "))
        self.btnOK.setText(_translate("digWithdraw", "OK"))
        self.lblCustomerName_3.setText(_translate("digWithdraw", "Customer: "))
        self.txtamount.setPlaceholderText(_translate("digWithdraw", "Multiple of 100 is allowed"))
        self.lblBalance_3.setText(_translate("digWithdraw", "Maximum allowed: 5000"))
        self.btnExit.setText(_translate("digWithdraw", "Exit"))
